export const COMMON_SKILLS = [
    // Programming Languages
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "SQL",
    "HTML",
    "CSS",

    // Frameworks & Libraries
    "React",
    "React Native",
    "Next.js",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Laravel",
    "Ruby on Rails",
    "Flutter",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Redux",
    "GraphQL",

    // Databases
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Firebase",
    "Supabase",
    "DynamoDB",

    // Cloud & DevOps
    "AWS",
    "Google Cloud Platform",
    "Azure",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitHub Actions",
    "Terraform",
    "Linux",
    "Nginx",
    "CI/CD",

    // Tools & Platforms
    "Git",
    "GitHub",
    "GitLab",
    "Jira",
    "Figma",
    "Adobe XD",
    "Photoshop",
    "Illustrator",
    "Postman",

    // Other Skills
    "Agile",
    "Scrum",
    "Project Management",
    "Data Analysis",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "UI/UX Design",
    "SEO",
    "Technical Writing",
    "Public Speaking"
];
